# Generated by Django 4.2 on 2025-06-11 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationalvideo',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='videocategory',
            options={'verbose_name_plural': 'Video Categories'},
        ),
        migrations.RemoveField(
            model_name='educationalvideo',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='educationalvideo',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='videocategory',
            name='created_at',
        ),
        migrations.AddField(
            model_name='educationalvideo',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationalvideo',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='educationalvideo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='education.videocategory'),
        ),
        migrations.AlterField(
            model_name='educationalvideo',
            name='duration',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='educationalvideo',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videocategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='VideoView',
        ),
    ]
