services:
  - type: web
    name: smartfarm-backend
    env: python
    buildCommand: |
      pip install -r backend/requirements.txt
      python backend/manage.py migrate --noinput
    startCommand: |
      cd backend && gunicorn smartfarm_backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: smartfarm_backend.settings
      - key: PYTHONPATH
        value: /opt/render/project/src/backend:/opt/render/project/src
      - key: DATABASE_URL
        value: postgresql://smartfarm_django_user:wcMIFXZiTlLuHNwC8uj1vK2LRysSsDpN@dpg-d22fibfgi27c73etq4vg-a.oregon-postgres.render.com/smartfarm_django
      - key: REACT_APP_WEATHER_API_KEY
        value: 67d420588c363ed048911e7549549c98
