services:
  - type: web
    name: smartfarm-backend
    env: python
    buildCommand: |
      pip install -r backend/requirements.txt
    startCommand: |
      gunicorn backend.smartfarm_backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: smartfarm_backend.settings
      - key: PYTHONPATH
        value: /opt/render/project/src