# Generated by Django 4.2.23 on 2025-07-17 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='equipmentrentalrequest',
            options={'ordering': ['-created_at']},
        ),
    ]
