# Generated by Django 4.2 on 2025-07-18 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_equipment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='equipmentrentalrequest',
            options={},
        ),
    ]
