# Generated by Django 4.2 on 2025-07-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_equipment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentrentalrequest',
            name='operation_location',
            field=models.CharField(default='Not specified', help_text='Location where the equipment will be used', max_length=200),
            preserve_default=False,
        ),
    ]
