# Generated by Django 4.2 on 2025-07-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_equipmentrentalrequest_operation_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentrentalrequest',
            name='payment_method',
            field=models.CharField(default='Cash on Delivery', max_length=50),
        ),
    ]
