# Generated by Django 4.2 on 2025-07-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_equipmentrentalrequest_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit'), ('mobile', 'Mobile Money')], default='cash', help_text='Preferred payment method for renting this equipment.', max_length=50),
        ),
    ]
