# Generated by Django 4.2 on 2025-07-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_equipment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='terms_and_conditions',
            field=models.TextField(default='Equipment should be used responsibly. Any damage caused by the farmer will result in a penalty. Equipment is rented for a maximum of one week.', help_text='Terms and conditions for renting this equipment.'),
        ),
    ]
