# Generated by Django 4.2.23 on 2025-07-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='transportrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='transport',
            name='price_per_trip',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='vehicle_name',
        ),
        migrations.AddField(
            model_name='transport',
            name='capacity',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transport',
            name='price_per_km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transport',
            name='vehicle_type',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='cargo_details',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='delivery_location',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='pickup_location',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
    ]
