# Generated by Django 4.2.23 on 2025-07-17 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0003_alter_transport_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportrequest',
            name='farmer',
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='requestor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_transport_requests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
