# Generated by Django 4.2 on 2025-07-18 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0004_rename_farmer_to_requestor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transport',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transportrequest',
            options={},
        ),
        migrations.RenameField(
            model_name='transport',
            old_name='price_per_km',
            new_name='price_per_trip',
        ),
        migrations.RenameField(
            model_name='transport',
            old_name='capacity',
            new_name='vehicle_name',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='vehicle_type',
        ),
        migrations.RemoveField(
            model_name='transportrequest',
            name='cargo_details',
        ),
        migrations.RemoveField(
            model_name='transportrequest',
            name='delivery_location',
        ),
        migrations.RemoveField(
            model_name='transportrequest',
            name='pickup_location',
        ),
        migrations.RemoveField(
            model_name='transportrequest',
            name='requestor',
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
