# Generated by Django 4.2 on 2025-07-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_alter_transport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
    ]
