# Generated by Django 4.2 on 2025-07-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_transport_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequest',
            name='cargo_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='delivery_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
