# Generated by Django 4.2 on 2025-07-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_transportrequest_cargo_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequest',
            name='payment_method',
            field=models.CharField(default='Cash on Delivery', max_length=50),
        ),
    ]
