# Generated by Django 4.2 on 2025-07-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_transportrequest_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit'), ('mobile', 'Mobile Money')], default='cash', help_text='Preferred payment method for transport services.', max_length=50),
        ),
    ]
