# Generated by Django 4.2.23 on 2025-07-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('text', 'Text')], max_length=10)),
                ('language', models.CharField(help_text='e.g. English, Arabic, Juba Arabic', max_length=50)),
                ('file', models.FileField(upload_to='education_resources/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
