# Generated by Django 4.2 on 2025-07-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationalresource',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='educationalresource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='educationalresource',
            name='resource_type',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('text', 'Text'), ('document', 'Document'), ('image', 'Image')], max_length=10),
        ),
    ]
