# Generated by Django 4.2 on 2025-07-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_educationalresource_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalresource',
            name='resource_type',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio')], max_length=10),
        ),
    ]
