# Generated by Django 4.2 on 2025-06-11 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_educationalvideo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationalvideo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Educational Video', 'verbose_name_plural': 'Educational Videos'},
        ),
        migrations.AlterModelOptions(
            name='videocategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Video Categories'},
        ),
        migrations.AddField(
            model_name='educationalvideo',
            name='thumbnail_file',
            field=models.ImageField(blank=True, help_text='Upload a thumbnail image', null=True, upload_to='video_thumbnails/'),
        ),
        migrations.AddField(
            model_name='educationalvideo',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload a video file (MP4, AVI, MOV, etc.)', null=True, upload_to='educational_videos/'),
        ),
        migrations.AddField(
            model_name='videocategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 11, 13, 52, 54, 239177, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='educationalvideo',
            name='duration',
            field=models.CharField(blank=True, help_text='Format: MM:SS or HH:MM:SS', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='educationalvideo',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Or provide a thumbnail URL', null=True),
        ),
        migrations.AlterField(
            model_name='educationalvideo',
            name='video_url',
            field=models.URLField(blank=True, help_text='Or provide a video URL (YouTube, Vimeo, etc.)', null=True),
        ),
    ]
