# Generated by Django 4.2.23 on 2025-07-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
