# Generated by Django 4.2.23 on 2025-07-17 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_productorder_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productorder',
            options={'ordering': ['-created_at']},
        ),
    ]
