# Generated by Django 4.2 on 2025-07-18 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_product_options_alter_productorder_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productorder',
            options={},
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='quantity',
        ),
    ]
