# Generated by Django 4.2 on 2025-07-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='payment_method',
            field=models.CharField(default='Cash on Delivery', max_length=50),
        ),
    ]
