# Generated by Django 4.2 on 2025-07-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit'), ('mobile', 'Mobile Money')], default='cash', help_text='Preferred payment method for transactions.', max_length=50),
        ),
    ]
